language: go
go:
  - 1.9.x
  - 1.10.x
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/codegangsta/negroni
script:
  - go test -v -race -tags=integration -coverprofile=coverage.out
  - goveralls -service=travis-ci -coverprofile=coverage.out
